/*
  BA-LA-BAYT TEXT / טקסט האתר
  Organizers: this is the ONLY file to edit for most website wording.
  Edit words BETWEEN quote marks. Keep punctuation, commas, and keys intact.
  'en' is English; 'he' is Hebrew. Instructions in START-HERE.md.
*/
window.BALABAYT_COPY = {
    en: {
      skip:'Skip to content',brandSubtitle:'Israeli Community Club · Rockville',navAbout:'About',navEvents:'Events',navVisit:'Visit',navSupport:'Get involved',
      heroEyebrow:'WELCOME TO BA-LA-BAYT · ROCKVILLE, MD',heroTitle:'Good company.<br>A place to belong.',heroText:'An open, welcoming gathering place for the local Israeli and Jewish community, and friends. Come meet people, share stories, and make something happen together.',heroEvents:'Explore our events ↗',heroDiscover:'Get to know us',heroSchedule:'Usually one Saturday a month · 8:00–11:30 PM',artCaption:'A LITTLE PIECE OF HOME',
      stripWhereTitle:'Rockville, Maryland',stripWhereText:'Location shared with participants for each event',stripWhenTitle:'Saturday evenings',stripWhenText:'Monthly gatherings · dates announced separately',stripWhoTitle:'Everyone is welcome',stripWhoText:'Members, neighbors and friends',
      aboutEyebrow:'WHO WE ARE',aboutTitle:'A community is built one evening at a time.',aboutLead:'Ba-La-Bayt is a volunteer-run social space for the local Israeli and Jewish community in the Rockville area.',aboutBody:"It's a place to catch up with old friends, meet new people, enjoy community activities, and bring ideas to life. The club is organized by members of the community, and everyone is encouraged to take part in whatever way they can.",aboutLink:'Have an idea? Write to us ↗',valuesLabel:'WHAT MAKES IT WORK',
      value1Title:'People first',value1Body:'A relaxed, welcoming place to connect and spend time together.',value2Title:'Community-led',value2Body:'Local volunteers help with events, the bar, and everyday logistics.',value3Title:'Built to grow',value3Body:'Event income, membership contributions, and donations go back into club activities and community events.',
      eventsEyebrow:'MARK YOUR CALENDAR',eventsTitle:"What's happening",eventsIntro:'Good conversations, familiar faces, and community activities. Confirmed upcoming dates will appear here.',eventsFoot:'Want to hear about the next gathering?',eventsEmail:'Contact the organizers →',emptyTitle:'More gatherings are on the way.',emptyText:'There are no confirmed upcoming events posted yet. Check back soon, or get in touch to hear about the next one.',register:'Registration & details ↗',eventDetails:'Event details ↗',eventDetails:'Details',
      visitEyebrow:'COME BY',visitTitle:'See you at the next gathering.',visitLead:'We meet in the Rockville area. We generally get together one Saturday evening each month; please check event announcements for the exact date.',visitDirections:'Ask about the next gathering ↗',locationKicker:'GATHERING DETAILS',locationDay:'Usually one Saturday per month',locationNote:'Exact arrangements are provided in event announcements.',
      supportEyebrow:'PITCH IN',supportTitle:'A club shaped by its community.',supportText:'Ba-La-Bayt relies on volunteers and community contributions. Help with an event, lend a hand behind the scenes, or support future gatherings.',donateButton:'Join / support the club ↗',volunteerButton:"I'd like to volunteer",fees:'Membership contributions listed in the club overview: $75 individual · $125 family. Please check with the organizers for current details.',qrTitle:'Support Ba-La-Bayt',qrText:"Scan to open the club's join and donation page.",qrSmall:'Donations and membership · external link',
      footerLine:'An Israeli community gathering place in Rockville, Maryland.',footerContact:'GET IN TOUCH',whatsapp:'· text / WhatsApp',footerCopyright:'© Ba-La-Bayt Community Club. Made for the community.',backTop:'Back to top ↑',pageTitle:'Ba-La-Bayt | Israeli Community Club',metaDescription:'Ba-La-Bayt is an Israeli community social club in Rockville, Maryland. Join us for gatherings, activities and community events.'
    },
    he: {
      skip:'דלגו לתוכן',brandSubtitle:'המועדון הקהילתי הישראלי · רוקוויל',navAbout:'עלינו',navEvents:'אירועים',navVisit:'מתי נפגשים',navSupport:'לוקחים חלק',
      heroEyebrow:'ברוכים הבאים לבעלבית · רוקוויל, מרילנד',heroTitle:'חברים טובים.<br>מקום להרגיש בבית.',heroText:'מקום מפגש פתוח ומזמין לקהילה הישראלית והיהודית באזור, ולחברים. נפגשים, מכירים אנשים, מחליפים חוויות ויוצרים ביחד דברים חדשים.',heroEvents:'לכל האירועים ↗',heroDiscover:'קצת עלינו',heroSchedule:'בדרך כלל שבת אחת בחודש · 20:00–23:30',artCaption:'קצת להרגיש בבית',
      stripWhereTitle:'רוקוויל, מרילנד',stripWhereText:'Location shared with participants for each event',stripWhenTitle:'מוצאי שבת',stripWhenText:'מפגשים חודשיים · תאריכים יפורסמו בנפרד',stripWhoTitle:'כולם מוזמנים',stripWhoText:'חברי המועדון, שכנים וחברים',
      aboutEyebrow:'מי אנחנו',aboutTitle:'קהילה בונים, מפגש אחרי מפגש.',aboutLead:'בעלבית הוא מרחב חברתי שמופעל בהתנדבות עבור הקהילה הישראלית והיהודית באזור רוקוויל.',aboutBody:'זה מקום לפגוש חברים ותיקים, להכיר אנשים חדשים, להשתתף בפעילויות ולהוציא רעיונות לפועל. חברי הקהילה מנהלים את הפעילות, וכולם מוזמנים לקחת חלק ולתרום כפי יכולתם.',aboutLink:'יש לכם רעיון? כתבו לנו ↗',valuesLabel:'מה עומד מאחורי המועדון',
      value1Title:'קודם כול אנשים',value1Body:'מקום נעים ופתוח למפגש, לשיחה ולבילוי משותף.',value2Title:'הקהילה מובילה',value2Body:'מתנדבים מהקהילה מסייעים בארגון האירועים, בניהול הבר ובלוגיסטיקה.',value3Title:'גדלים ביחד',value3Body:'הכנסות מאירועים, דמי חברות ותרומות חוזרות לפעילות המועדון ולאירועי הקהילה.',
      eventsEyebrow:'רושמים ביומן',eventsTitle:'מה קורה בקרוב',eventsIntro:'מפגשים, שיחות ופעילויות קהילתיות. תאריכים מאושרים יתפרסמו כאן.',eventsFoot:'רוצים לשמוע על המפגש הבא?',eventsEmail:'צרו קשר עם המארגנים ←',emptyTitle:'נתראה במפגשים הבאים.',emptyText:'כרגע לא פורסמו כאן אירועים קרובים עם תאריך מאושר. כדאי לחזור בקרוב או ליצור קשר לקבלת פרטים.',register:'להרשמה ולפרטים ↗',eventDetails:'לפרטי האירוע ↗',eventDetails:'פרטים',
      visitEyebrow:'בואו לבקר',visitTitle:'ניפגש במפגש הבא.',visitLead:'אנחנו נפגשים באזור רוקוויל. בדרך כלל אנחנו נפגשים במוצאי שבת פעם בחודש; מומלץ לבדוק את התאריך המדויק בפרסום האירוע.',visitDirections:'שאלו אותנו על המפגש הבא ↗',locationKicker:'פרטי המפגש',locationDay:'בדרך כלל שבת אחת בחודש',locationNote:'השעות והפרטים עשויים להשתנות בין אירועים.',
      supportEyebrow:'ביחד זה עובד',supportTitle:'המועדון הוא מה שאנחנו עושים ממנו.',supportText:'בעלבית פועל בזכות מתנדבים ותמיכה של הקהילה. אפשר לסייע באירוע, להתנדב מאחורי הקלעים או לתמוך במפגשים הבאים.',donateButton:'הצטרפות / תמיכה במועדון ↗',volunteerButton:'רוצים להתנדב',fees:'דמי החברות המופיעים במסמך המועדון: 75$ ליחיד · 125$ למשפחה. כדאי לברר עם המארגנים מה הסכומים המעודכנים.',qrTitle:'תומכים בבעלבית',qrText:'סרקו לפתיחת עמוד ההצטרפות והתרומה של המועדון.',qrSmall:'תרומות וחברות · קישור חיצוני',
      footerLine:'מקום מפגש קהילתי ישראלי ברוקוויל, מרילנד.',footerContact:'יוצרים קשר',whatsapp:'· הודעה / ווטסאפ',footerCopyright:'© בעלבית, המועדון הקהילתי. נבנה בשביל הקהילה.',backTop:'בחזרה למעלה ↑',pageTitle:'בעלבית | המועדון הקהילתי הישראלי',metaDescription:'בעלבית הוא מרחב מפגש חברתי לקהילה הישראלית והיהודית ברוקוויל, מרילנד. מצטרפים למפגשים, פעילויות ואירועי קהילה.'
    }
  };

